language: generic
sudo: required
services: 
  - docker

before_install: 
  - docker build -t avocadodev2050/docker-react -f Dockerfile.DEV .

script: 
  - docker run -e CI=true avocadodev2050/docker-react npm run test -- --coverage